CREATE TABLE "UM_AUDIT_TRAIL" 
(
    "AUDIT_TRAIL_ID" Number, 
    "USER_ID" VARCHAR2(2000 BYTE), 
    "ACTION_TYPE" VARCHAR2(1 BYTE), 
    "FUNC_ID" VARCHAR2(4 BYTE), 
    "OFFICE_CODE" VARCHAR2(4 BYTE), 
    "LOG_DATETIME" TIMESTAMP, 
    "JSESSIONID" VARCHAR2(40 BYTE),
    "IMMD_TOKEN" VARCHAR2(32 BYTE)
);

ALTER TABLE "UM_AUDIT_TRAIL" ADD PRIMARY KEY ("AUDIT_TRAIL_ID");

COMMENT ON COLUMN "UM_AUDIT_TRAIL"."AUDIT_TRAIL_ID" IS 'Primary key of UM_AUDIT_TRAIL';
COMMENT ON COLUMN "UM_AUDIT_TRAIL"."USER_ID" IS 'The unique id to identify the applicant/user';
COMMENT ON COLUMN "UM_AUDIT_TRAIL"."ACTION_TYPE" IS 'S = Search Actin, C = Create Action, U = Update Action';
COMMENT ON COLUMN "UM_AUDIT_TRAIL"."OFFICE_CODE" IS 'Office Code of Mapping in OFFICE Table';
COMMENT ON COLUMN "UM_AUDIT_TRAIL"."LOG_DATETIME" IS 'Record the logging time';
COMMENT ON COLUMN "UM_AUDIT_TRAIL"."JSESSIONID" IS 'The unique id for a submission/session. ';
COMMENT ON COLUMN "UM_AUDIT_TRAIL"."OFFICE_CODE" IS 'Office Code of Mapping in OFFICE Table';

CREATE TABLE "UM_SEARCH_AUDIT_TRAIL" 
(
    "AUDIT_TRAIL_ID" Number, 
    "SEQ_NO" NUMBER, 
    "SEARCH_TABLE_NAME" VARCHAR2(2000 BYTE), 
    "SEARCH_FIELD_NAME" VARCHAR2(1 BYTE), 
    "SEARCH_VALUE" VARCHAR2(4000 BYTE),
    "SEARCH_RESULT" VARCHAR2(1 BYTE)
);

COMMENT ON COLUMN "UM_SEARCH_AUDIT_TRAIL"."AUDIT_TRAIL_ID" IS 'AUDIT_TRAIL_ID of Mapping in UM_AUDIT_TRAIL';
COMMENT ON COLUMN "UM_SEARCH_AUDIT_TRAIL"."SEQ_NO" IS 'The sequence number of the searching criteria';
COMMENT ON COLUMN "UM_SEARCH_AUDIT_TRAIL"."SEARCH_TABLE_NAME" IS 'Searching table';
COMMENT ON COLUMN "UM_SEARCH_AUDIT_TRAIL"."SEARCH_FIELD_NAME" IS 'Searching field';
COMMENT ON COLUMN "UM_SEARCH_AUDIT_TRAIL"."SEARCH_VALUE" IS 'Searching value';
COMMENT ON COLUMN "UM_SEARCH_AUDIT_TRAIL"."SEARCH_RESULT" IS 'Y = Hit; N = No Hit';

CREATE TABLE "UM_ACTION_AUDIT_TRAIL" 
(
    "AUDIT_TRAIL_ID" Number, 
    "SEQ_NO" NUMBER, 
    "TABLE_NAME" VARCHAR2(4 BYTE), 
    "FIELD_NAME" VARCHAR2(4 BYTE), 
    "VALUE_OLD" TIMESTAMP, 
    "VALUE_NEW" VARCHAR2(40 BYTE)
);
COMMENT ON COLUMN "UM_ACTION_AUDIT_TRAIL"."AUDIT_TRAIL_ID" IS 'AUDIT_TRAIL_ID of Mapping in UM_AUDIT_TRAIL';
COMMENT ON COLUMN "UM_ACTION_AUDIT_TRAIL"."SEQ_NO" IS 'The sequence number of the update elements';
COMMENT ON COLUMN "UM_ACTION_AUDIT_TRAIL"."TABLE_NAME" IS 'Affect table';
COMMENT ON COLUMN "UM_ACTION_AUDIT_TRAIL"."FIELD_NAME" IS 'Affect field';
COMMENT ON COLUMN "UM_ACTION_AUDIT_TRAIL"."VALUE_OLD" IS 'Old value';
COMMENT ON COLUMN "UM_ACTION_AUDIT_TRAIL"."VALUE_NEW" IS 'New value';



