
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ws.cds.immd.v1;

import com.pccw.immd.adminfunc.domain.*;
import com.pccw.immd.adminfunc.repository.*;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-22T15:10:28.098+08:00
 * Generated source version: 3.2.3
 *
 */
//
@javax.jws.WebService(
        serviceName = "EnquireTransactionGroupServiceWSImplService",
        portName = "EnquireTransactionGroupServiceWSImplPort",
        targetNamespace = "http://txgroup.cds.icons.immd/",
        wsdlLocation = "wsdl/enquireTranGpSvc.wsdl",
        endpointInterface = "ws.cds.immd.v1.EnquireTransactionGroupServiceWS")
@Service("enquireTransactionGroupServiceWSImplPortImpl")
public class EnquireTransactionGroupServiceWSImplPortImpl implements EnquireTransactionGroupServiceWS {

    @Autowired
    @Qualifier("roleGroupRepository")
    private RoleGroupRepository roleGroupRepository;

    @Autowired
    @Qualifier("groupRepository")
    private GroupRepository groupRepository;

    @Autowired
    @Qualifier("groupFuncRepository")
    private GroupFuncRepository groupFuncRepository;

    @Autowired
    @Qualifier("funcRepository")
    private FuncRepository funcRepository;

    @Autowired
    @Qualifier("roleRepository")
    RoleRepository roleRepository;

    private static final Logger LOG = Logger.getLogger(EnquireTransactionGroupServiceWSImplPortImpl.class.getName());

    public EnquireTransactionGroupServiceWSImplPortImpl(){}

    /* (non-Javadoc)
     * @see ws.cds.immd.v1.EnquireTransactionGroupServiceWS#enquireAllData()*
     */
    public RoleTxgpTxidDTO enquireAllData() throws VLDExceptionException,  CoreAppExceptionException   {
        LOG.info("Executing operation enquireAllData");
        try {
            RoleTxgpTxidDTO roleTxgpTxidDTO = new RoleTxgpTxidDTO();
            List<Role> roleIdList = roleRepository.findAll();
            for (Role roleId: roleIdList) {
                RoleTxgp roleTxgp = new RoleTxgp();
                roleTxgp.setRoleCD(roleId.getRoleId());
                List<RoleGroup> roleGroupList = roleGroupRepository.findAllByRoleId(roleId.getRoleId());

                for (RoleGroup groupID: roleGroupList) {
                    roleTxgp.getTxGps().add(groupID.getGroupId());
                }
                roleTxgpTxidDTO.getRoleTxgps().add(roleTxgp);
            }

            List<Group> groupIdDescList = groupRepository.findAll();
            for (Group group : groupIdDescList) {
                Txgp txgp = new Txgp();
                txgp.setTxGp(group.getGroupId());
                txgp.setTxGpDesc(group.getGroupDesc());
                roleTxgpTxidDTO.getTxgps().add(txgp);
            }
            LOG.debug("enquireAllDataResponse: " + roleTxgpTxidDTO);
            return roleTxgpTxidDTO;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ws.cds.immd.v1.EnquireTransactionGroupServiceWS#enquireTransactionGroup(java.util.List<java.lang.String> roleCdList)*
     */
    public List<TransGrpRoleDTO> enquireTransactionGroup(List<String> roleCdList) throws VLDExceptionException,  CoreAppExceptionException   {
        LOG.info("Executing operation enquireTransactionGroup");
        System.out.println(roleCdList);
        try {
            List<TransGrpRoleDTO> transGrpRoleDTO = new ArrayList<TransGrpRoleDTO>();
            for (String roleCd : roleCdList) {
                List<RoleGroup> roleGroupList = roleGroupRepository.findAllByRoleId(roleCd);
                for (RoleGroup roleGroup : roleGroupList) {
                    TransGrpRoleDTO roleGroupDescList = new TransGrpRoleDTO();
                    roleGroupDescList.setRoleCd(roleCd);
                    Group groupID = groupRepository.findByGroupId(roleGroup.getGroupId());
                    roleGroupDescList.setTxGrpId(groupID.getGroupId());
                    roleGroupDescList.setTxGrpDesc(groupID.getGroupDesc());
                    transGrpRoleDTO.add(roleGroupDescList);
                }
            }
            LOG.debug("EnquireTransactionGroupResponse: " + transGrpRoleDTO);
            return transGrpRoleDTO;

        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ws.cds.immd.v1.EnquireTransactionGroupServiceWS#enquireTxIDsByRoleCd(java.lang.String roleCd)*
     */
    public List<Txid> enquireTxIDsByRoleCd(String roleCd) {
        LOG.info("Executing operation enquireTxIDsByRoleCd");
        try {
            List<Txid> txidList = new ArrayList<>();
            List<RoleGroup> groupIdList = roleGroupRepository.findAllByRoleId(roleCd);
            for (RoleGroup groupID : groupIdList) {
                List<GroupFunc> groupFunc = groupFuncRepository.findAllByGroupId(groupID.getGroupId());
                for (GroupFunc funcIdDesc : groupFunc ) {
                    Txid txid = new Txid();
                    Func txIdDesc = funcRepository.findByFuncId(funcIdDesc.getFuncId());
                    txid.setTxid(txIdDesc.getFuncId());
                    txid.setTxidDesc(txIdDesc.getFuncDesc());
                    txidList.add(txid);
                }
            }
            LOG.debug("EnquireTxIDsByRoleCdResponse: " + txidList);
            return txidList;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
