package immd.icons.cds.txgroup;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import ws.cds.immd.v1.EnquireTransactionGroupServiceWS;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-04-05T20:38:59.156+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "EnquireTransactionGroupServiceWSImplService", 
                  wsdlLocation = "file:enquireTranGpSvc.wsdl",
                  targetNamespace = "http://txgroup.cds.icons.immd/") 
public class EnquireTransactionGroupServiceWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://txgroup.cds.icons.immd/", "EnquireTransactionGroupServiceWSImplService");
    public final static QName EnquireTransactionGroupServiceWSImplPort = new QName("http://txgroup.cds.icons.immd/", "EnquireTransactionGroupServiceWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:enquireTranGpSvc.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EnquireTransactionGroupServiceWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:enquireTranGpSvc.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EnquireTransactionGroupServiceWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnquireTransactionGroupServiceWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnquireTransactionGroupServiceWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EnquireTransactionGroupServiceWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EnquireTransactionGroupServiceWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EnquireTransactionGroupServiceWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EnquireTransactionGroupServiceWS
     */
    @WebEndpoint(name = "EnquireTransactionGroupServiceWSImplPort")
    public EnquireTransactionGroupServiceWS getEnquireTransactionGroupServiceWSImplPort() {
        return super.getPort(EnquireTransactionGroupServiceWSImplPort, EnquireTransactionGroupServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnquireTransactionGroupServiceWS
     */
    @WebEndpoint(name = "EnquireTransactionGroupServiceWSImplPort")
    public EnquireTransactionGroupServiceWS getEnquireTransactionGroupServiceWSImplPort(WebServiceFeature... features) {
        return super.getPort(EnquireTransactionGroupServiceWSImplPort, EnquireTransactionGroupServiceWS.class, features);
    }

}
