/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.pccw.immd.adminfunc.web.rest.intr;



import com.pccw.immd.adminfunc.dto.UserDTO;
import com.pccw.immd.adminfunc.dto.ValidationerrorDTO;
import com.pccw.immd.adminfunc.web.rest.LoginServicesApiController;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-01T03:56:21.323Z")

@Api(value = "adminfunc", description = "the adminfunc API")
public interface LoginServicesApi {

    @ApiOperation(value = "Test example for validation", notes = "Test example for validationf", response = String.class, tags={ "adminfunc","protected", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "Return success message", response = String.class),
        @ApiResponse(code = 400, message = "Return validation error", response = ValidationerrorDTO.class) })

    @RequestMapping(value = "/login/",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.POST)
    LoginServicesApiController.UpmsUser login(@ApiParam(value = "", required = true) @RequestBody  @Valid  UserDTO userDTO);

}
