

export const REDUCER_PAGE = {
    USER_LOGIN_PAGE: 'USER_LOGIN_PAGE',
    LANDING_PAGE: 'LANDING_PAGE',
}

export const AUTH_ACTION = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
}

export const USER_ATION = {
    CHANGE_PWD_REQUEST: 'CHANGE_PWD_REQUEST',
    CHANGE_PWD_SUCCESS: 'CHANGE_PWD_SUCCESS',
    CHANGE_PWD_FAIL: 'CHANGE_PWD_FAIL',
}

//
export const ACTION_TYPE = {
    // USER_LOGIN_MAIN_PAGE: 'USER_LOGIN_MAIN_PAGE',
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    // LANDING_MAIN_PAGE: 'LANDING_MAIN_PAGE',
}

