
CREATE TABLE "UM_AUDIT_TRAIL_SEARCH" 
(
    "AUDIT_TRAIL_ID" Number, 
    "USER_ID" VARCHAR2(2000 BYTE), 
    "ACTION_TYPE" VARCHAR2(10 BYTE), 
    "FUNC_ID" VARCHAR2(4 BYTE), 
    "OFFICE_CODE" VARCHAR2(4 BYTE), 
    "LOG_DATETIME" TIMESTAMP, 
    "JSESSIONID" VARCHAR2(40 BYTE),
    "IMMD_TOKEN" VARCHAR2(32 BYTE), 
    "SEQ_NO" NUMBER, 
    "SEARCH_TABLE_NAME" VARCHAR2(100 BYTE), 
    "SEARCH_FIELD_NAME" VARCHAR2(100 BYTE), 
    "SEARCH_VALUE" VARCHAR2(4000 BYTE),
    "SEARCH_RESULT" VARCHAR2(1 BYTE)
);


COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."AUDIT_TRAIL_ID" IS 'Primary key of UM_AUDIT_TRAIL_SEARCH';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."USER_ID" IS 'The unique id to identify the applicant/user';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."ACTION_TYPE" IS 'S = Search Actin, C = Create Action, U = Update Action';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."OFFICE_CODE" IS 'Office Code of Mapping in OFFICE Table';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."LOG_DATETIME" IS 'Record the logging time';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."JSESSIONID" IS 'The unique id for a submission/session. ';COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."SEQ_NO" IS 'The sequence number of the searching criteria';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."SEARCH_TABLE_NAME" IS 'Searching table';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."SEARCH_FIELD_NAME" IS 'Searching field';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."SEARCH_VALUE" IS 'Searching value';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_SEARCH"."SEARCH_RESULT" IS 'Y = Hit; N = No Hit';

CREATE TABLE "UM_AUDIT_TRAIL_ACTION" 
(
    "AUDIT_TRAIL_ID" Number, 
    "USER_ID" VARCHAR2(2000 BYTE), 
    "ACTION_TYPE" VARCHAR2(10 BYTE), 
    "FUNC_ID" VARCHAR2(4 BYTE), 
    "OFFICE_CODE" VARCHAR2(4 BYTE), 
    "LOG_DATETIME" TIMESTAMP, 
    "JSESSIONID" VARCHAR2(40 BYTE),
    "IMMD_TOKEN" VARCHAR2(32 BYTE), 
    "SEQ_NO" NUMBER, 
    "TABLE_NAME" VARCHAR2(100 BYTE), 
    "FIELD_NAME" VARCHAR2(100 BYTE), 
    "VALUE_OLD" VARCHAR2(4000 BYTE), 
    "VALUE_NEW" VARCHAR2(4000 BYTE)
);
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."AUDIT_TRAIL_ID" IS 'Primary key of UM_AUDIT_TRAIL_ACTION';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."USER_ID" IS 'The unique id to identify the applicant/user';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."ACTION_TYPE" IS 'S = Search Actin, C = Create Action, U = Update Action';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."OFFICE_CODE" IS 'Office Code of Mapping in OFFICE Table';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."LOG_DATETIME" IS 'Record the logging time';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."JSESSIONID" IS 'The unique id for a submission/session. ';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."SEQ_NO" IS 'The sequence number of the update elements';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."TABLE_NAME" IS 'Affect table';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."FIELD_NAME" IS 'Affect field';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."VALUE_OLD" IS 'Old value';
COMMENT ON COLUMN "UM_AUDIT_TRAIL_ACTION"."VALUE_NEW" IS 'New value';



