--------------------------------------------------------
--  DDL for Table UM_GROUP_FUNC
--------------------------------------------------------

  CREATE TABLE "UM_GROUP_FUNC"
   (	"GROUP_ID" VARCHAR2(16 BYTE), 
	"FUNC_ID" VARCHAR2(8 BYTE)
   )  ;

  ALTER TABLE "UM_GROUP_FUNC" MODIFY ("GROUP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "UM_GROUP_FUNC" MODIFY ("FUNC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "UM_GROUP_FUNC" ADD CONSTRAINT "UM_GROUP_FUNC_PK" PRIMARY KEY ("GROUP_ID", "FUNC_ID")



Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('BR Sup','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('BR Sup','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('BR User','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('CDCM','CCM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('CDCM','CDM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('CDCM','COM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('CDCM','CPM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('COE Submission','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Delete_App','DAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ESAppln Sup','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ESAppln Sup','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ESAppln Sup','SDS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ESAppln User','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ESAppln User','SDS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ESBooking Sup','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ESBooking Sup','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ESBooking User','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Email Alert','QAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Enq_Code','ECE0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('INV Sup','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('INV Sup','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('INV User','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Imp_Announcement','IAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('MA001','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('MARG1','ADM0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('MARG1','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('MARG1','IAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','ADM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','ADM0005');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','ADM0007');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','DAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','ECE0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','EFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','EFN0010');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','EFN0019');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','IAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','MQM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','PFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','PFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','QAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','QAM0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','QRM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','QRM0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','RIS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW','VQM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW_DEL_USER','ADM0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PCCW_DEL_USER','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PMT_Supervisor','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PMT_User','EFN0019');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('PMT_User','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Quota Main','EFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Quota Maint','EFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Quota Transfer','MQM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Quota_Release','QRM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_Sup','ADM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_Sup','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_Sup','DAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_Sup','EFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_Sup','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_Sup','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_Sup','ROA0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_Sup','SDS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_User','DAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_User','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_User','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_User','ROA0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ROA_User','SDS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('TD Sup_Virtual','EFN0019');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('TD Sup_Virtual','VQM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('Test1','ADM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('User','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('User','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('User','PFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('User','PFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('User Main','ADM0003');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('User Main','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('a','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('admin','ADM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('admin','EFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('admin','EFN0019');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('admin','MQM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('admin','PFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('admin','PFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroup','ADM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroup','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','ADM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','ADM0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','ADM0005');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','ADM0006');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','ADM0007');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0003');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0005');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0006');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0007');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0008');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0009');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0010');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0011');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0012');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0013');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0014');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0015');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0016');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0017');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','EFN0018');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','PFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','PFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('allgroups','RIS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('bbb','ECE0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ACM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ADM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ADM0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ADM0005');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ADM0006');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ADM0007');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','DAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ECE0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','EFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','IAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','MQM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','PFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','PFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','RIS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','ROA0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('e-Services','SDS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('ip block','ACM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('test2','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ACM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ADM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ADM0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ADM0004');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ADM0005');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ADM0006');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ADM0007');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','DAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ECE0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','EFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','EFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','EFN0010');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','EFN0017');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','EFN0019');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','GFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','IAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','MQM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','PFN0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','PFN0002');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','QAM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','QRM0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','ROA0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('testinga','SDS0001');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('wingwong','EFN0006');
Insert into UM_GROUP_FUNC (GROUP_ID,FUNC_ID) values ('wingwong','EFN0007');