package com.pccw.immd.adminfunc.domain;
// Generated Apr 25, 2018 1:46:10 PM by Hibernate Tools 5.0.6.Final


import javax.persistence.*;
import java.io.Serializable;

/**
 * SctlSvcTicket generated by hbm2java
 */
@Entity
@Table(name="SCTL_SVC_TICKET")
public class SctlSvcTicket implements Serializable {


     private SctlSvcTicketId id;

    public SctlSvcTicket() {
    }

    public SctlSvcTicket(SctlSvcTicketId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ticketId", column=@Column(name="TICKET_ID", length=20) ), 
        @AttributeOverride(name="svcId", column=@Column(name="SVC_ID", length=3) ), 
        @AttributeOverride(name="allotedDate", column=@Column(name="ALLOTED_DATE", columnDefinition = "TIMESTAMP") ),
        @AttributeOverride(name="isClawback", column=@Column(name="IS_CLAWBACK", length=1) ), 
        @AttributeOverride(name="clawbackSvcId", column=@Column(name="CLAWBACK_SVC_ID", length=3) ) } )
    public SctlSvcTicketId getId() {
        return this.id;
    }
    
    public void setId(SctlSvcTicketId id) {
        this.id = id;
    }




}


