package com.pccw.immd.adminfunc.domain;
// Generated Apr 25, 2018 1:46:10 PM by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;
import java.util.Date;

/**
 * SctlSvcTicketId generated by hbm2java
 */
@Embeddable
public class SctlSvcTicketId  implements Serializable {


     private String ticketId;
     private String svcId;
     private Date allotedDate;
     private String isClawback;
     private String clawbackSvcId;

    public SctlSvcTicketId() {
    }

    public SctlSvcTicketId(String ticketId, String svcId, Date allotedDate, String isClawback, String clawbackSvcId) {
       this.ticketId = ticketId;
       this.svcId = svcId;
       this.allotedDate = allotedDate;
       this.isClawback = isClawback;
       this.clawbackSvcId = clawbackSvcId;
    }
   


    @Column(name="TICKET_ID", length=20)
    public String getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }


    @Column(name="SVC_ID", length=3)
    public String getSvcId() {
        return this.svcId;
    }
    
    public void setSvcId(String svcId) {
        this.svcId = svcId;
    }


    @Column(name="ALLOTED_DATE")
    public Date getAllotedDate() {
        return this.allotedDate;
    }
    
    public void setAllotedDate(Date allotedDate) {
        this.allotedDate = allotedDate;
    }


    @Column(name="IS_CLAWBACK", length=1)
    public String getIsClawback() {
        return this.isClawback;
    }
    
    public void setIsClawback(String isClawback) {
        this.isClawback = isClawback;
    }


    @Column(name="CLAWBACK_SVC_ID", length=3)
    public String getClawbackSvcId() {
        return this.clawbackSvcId;
    }
    
    public void setClawbackSvcId(String clawbackSvcId) {
        this.clawbackSvcId = clawbackSvcId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SctlSvcTicketId) ) return false;
		 SctlSvcTicketId castOther = ( SctlSvcTicketId ) other; 
         
		 return ( (this.getTicketId()==castOther.getTicketId()) || ( this.getTicketId()!=null && castOther.getTicketId()!=null && this.getTicketId().equals(castOther.getTicketId()) ) )
 && ( (this.getSvcId()==castOther.getSvcId()) || ( this.getSvcId()!=null && castOther.getSvcId()!=null && this.getSvcId().equals(castOther.getSvcId()) ) )
 && ( (this.getAllotedDate()==castOther.getAllotedDate()) || ( this.getAllotedDate()!=null && castOther.getAllotedDate()!=null && this.getAllotedDate().equals(castOther.getAllotedDate()) ) )
 && ( (this.getIsClawback()==castOther.getIsClawback()) || ( this.getIsClawback()!=null && castOther.getIsClawback()!=null && this.getIsClawback().equals(castOther.getIsClawback()) ) )
 && ( (this.getClawbackSvcId()==castOther.getClawbackSvcId()) || ( this.getClawbackSvcId()!=null && castOther.getClawbackSvcId()!=null && this.getClawbackSvcId().equals(castOther.getClawbackSvcId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTicketId() == null ? 0 : this.getTicketId().hashCode() );
         result = 37 * result + ( getSvcId() == null ? 0 : this.getSvcId().hashCode() );
         result = 37 * result + ( getAllotedDate() == null ? 0 : this.getAllotedDate().hashCode() );
         result = 37 * result + ( getIsClawback() == null ? 0 : this.getIsClawback().hashCode() );
         result = 37 * result + ( getClawbackSvcId() == null ? 0 : this.getClawbackSvcId().hashCode() );
         return result;
   }   


}


