package com.pccw.immd.adminfunc.domain;
// Generated Apr 25, 2018 1:46:10 PM by Hibernate Tools 5.0.6.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * SctlSharePool generated by hbm2java
 */
@Entity
@Table(name="SCTL_SHARE_POOL")
public class SctlSharePool  implements Serializable {


     private BigDecimal poolId;
     private LocalDateTime lastAllotedDate;
     private LocalDateTime lastReleaseDate;
     private BigDecimal allotedCount;
     private BigDecimal totalCount;

    public SctlSharePool() {
    }

	
    public SctlSharePool(BigDecimal poolId) {
        this.poolId = poolId;
    }
    public SctlSharePool(BigDecimal poolId, LocalDateTime lastAllotedDate, LocalDateTime lastReleaseDate, BigDecimal allotedCount, BigDecimal totalCount) {
       this.poolId = poolId;
       this.lastAllotedDate = lastAllotedDate;
       this.lastReleaseDate = lastReleaseDate;
       this.allotedCount = allotedCount;
       this.totalCount = totalCount;
    }
   
     @Id 

    
    @Column(name="POOL_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getPoolId() {
        return this.poolId;
    }
    
    public void setPoolId(BigDecimal poolId) {
        this.poolId = poolId;
    }

    
    @Column(name="LAST_ALLOTED_DATE", columnDefinition = "TIMESTAMP")
    public LocalDateTime getLastAllotedDate() {
        return this.lastAllotedDate;
    }
    
    public void setLastAllotedDate(LocalDateTime lastAllotedDate) {
        this.lastAllotedDate = lastAllotedDate;
    }

    
    @Column(name="LAST_RELEASE_DATE", columnDefinition = "TIMESTAMP")
    public LocalDateTime getLastReleaseDate() {
        return this.lastReleaseDate;
    }
    
    public void setLastReleaseDate(LocalDateTime lastReleaseDate) {
        this.lastReleaseDate = lastReleaseDate;
    }

    
    @Column(name="ALLOTED_COUNT", precision=22, scale=0)
    public BigDecimal getAllotedCount() {
        return this.allotedCount;
    }
    
    public void setAllotedCount(BigDecimal allotedCount) {
        this.allotedCount = allotedCount;
    }

    
    @Column(name="TOTAL_COUNT", precision=22, scale=0)
    public BigDecimal getTotalCount() {
        return this.totalCount;
    }
    
    public void setTotalCount(BigDecimal totalCount) {
        this.totalCount = totalCount;
    }




}


